const musicStyle=document.createElement('link');musicStyle.rel='stylesheet';musicStyle.href='music.css';document.head.append(musicStyle);const birthdaySong=document.querySelector('#birthdaySong'),yaarSong=document.querySelector('#yaarSong'),musicToggle=document.querySelector('#musicToggle');let musicOn=true;
[birthdaySong,yaarSong].forEach(t=>t.volume=.56);
function wantedTrack(){const n=Number(document.querySelector('.scene.active')?.dataset.scene||0);return n===2||n===3?birthdaySong:yaarSong}
function stopTrack(t){if(!t.paused){t.pause();t.currentTime=0}}
function syncMusic(){const wanted=wantedTrack(),other=wanted===birthdaySong?yaarSong:birthdaySong;if(other)stopTrack(other);if(!wanted||!musicOn){stopTrack(birthdaySong);stopTrack(yaarSong);musicToggle.classList.remove('playing');return}wanted.play().then(()=>{musicToggle.classList.add('playing');musicToggle.querySelector('span').textContent=wanted===birthdaySong?'BIRTHDAY':'YAAR'}).catch(()=>{musicToggle.classList.remove('playing');musicToggle.querySelector('span').textContent='PLAY'})}
musicToggle.addEventListener('click',()=>{musicOn=!musicOn;musicToggle.querySelector('span').textContent=musicOn?'MUSIC':'MUTED';syncMusic()});
document.querySelector('#unlock').addEventListener('submit',()=>{if(document.querySelector('#pin').value==='2107'){musicOn=true;stopTrack(yaarSong);birthdaySong.volume=.56;birthdaySong.play().then(()=>{musicToggle.classList.add('playing');musicToggle.querySelector('span').textContent='BIRTHDAY'}).catch(()=>{musicToggle.querySelector('span').textContent='TAP TO PLAY'})}});
document.addEventListener('click',e=>{if(e.target.closest('#lightCandle,#makeWish,#blowCandle,#knife,[data-next],#back,#home,#replay'))setTimeout(syncMusic,20)},true);
const watcher=new MutationObserver(syncMusic);document.querySelectorAll('.scene').forEach(s=>watcher.observe(s,{attributes:true,attributeFilter:['class']}));document.addEventListener('pointerdown',()=>syncMusic(),{once:true,capture:true});document.addEventListener('keydown',()=>syncMusic(),{once:true,capture:true});syncMusic();
