const scenes=[...document.querySelectorAll('.scene')];
const introAudio=document.querySelector('#introSong');
const audio=document.querySelector('#birthdaySong');
const cakeAudio=document.querySelector('#cakeSong');
const finaleAudio=document.querySelector('#finaleSong');
const expectationAudio=document.querySelector('#expectationSong');
const musicToggle=document.querySelector('#musicToggle');
const progressFill=document.querySelector('#progressFill');
const chapterCount=document.querySelector('#chapterCount');
const backBtn=document.querySelector('#backBtn');
const canvas=document.querySelector('#confetti');
const ctx=canvas.getContext('2d');
const toast=document.querySelector('#toast');
const cakeTracks=['assets/birthday-song-01.mp3','assets/birthday-song-02.mp3','assets/birthday-song-03.mp3','assets/birthday-song-04.mp3'];
const cakeTrackLabels=[...document.querySelectorAll('[data-cake-track-label]')];
let current=0,playing=false,currentAudio=introAudio,expectationUnlocked=false,cakeTrackIndex=0,particles=[];

const birthdayCountdown=document.querySelector('#birthdayCountdown');
function renderBirthdayCountdown(){const now=new Date();let year=now.getFullYear(),target=new Date(year,6,23,0,0,0),end=new Date(year,6,24,0,0,0);if(now>=target&&now<end){birthdayCountdown.className='birthday-countdown is-today';birthdayCountdown.textContent='✦ IT’S TIME NOW!! HAPPY BIRTHDAY, NANDINI ✦';return}if(now>=end)target=new Date(year+1,6,23,0,0,0);const today=new Date(now.getFullYear(),now.getMonth(),now.getDate()),days=Math.max(1,Math.round((target-today)/86400000));birthdayCountdown.className='birthday-countdown birthday-countdown--days';birthdayCountdown.innerHTML=`<span><b>${String(days).padStart(2,'0')}</b><small>${days===1?'day':'days'} to go</small></span>`}
renderBirthdayCountdown();setInterval(renderBirthdayCountdown,60000);

function sizeCanvas(){const d=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*d;canvas.height=innerHeight*d;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0)}
function burst(x=innerWidth/2,y=innerHeight/2,count=70,hearts=false){const colors=['#f8b5ca','#fff1db','#f1be69','#c64d79','#fff'];for(let i=0;i<count;i++)particles.push({x,y,vx:(Math.random()-.5)*10,vy:-3-Math.random()*7,g:.12+Math.random()*.1,life:65+Math.random()*50,size:3+Math.random()*7,color:colors[i%colors.length],heart:hearts&&i%3===0,rot:Math.random()*6})}
function animate(){ctx.clearRect(0,0,innerWidth,innerHeight);particles=particles.filter(p=>p.life>0);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=p.g;p.life--;p.rot+=.12;ctx.save();ctx.globalAlpha=Math.min(1,p.life/40);ctx.translate(p.x,p.y);ctx.rotate(p.rot);ctx.fillStyle=p.color;if(p.heart){ctx.font=`${p.size*3}px serif`;ctx.fillText('♡',-p.size,-p.size)}else ctx.fillRect(-p.size/2,-p.size/2,p.size,p.size*.65);ctx.restore()});requestAnimationFrame(animate)}
function showToast(message){toast.textContent=message;toast.classList.add('is-visible');clearTimeout(showToast.t);showToast.t=setTimeout(()=>toast.classList.remove('is-visible'),2200)}
function musicForScene(index=current){return index<2?introAudio:index===2?cakeAudio:index===6?(expectationUnlocked?expectationAudio:finaleAudio):audio}
function startMusic(){const wanted=musicForScene();if(currentAudio!==wanted){currentAudio.pause();currentAudio=wanted}currentAudio.volume=.42;currentAudio.play().then(()=>{playing=true;musicToggle.classList.add('is-playing');musicToggle.setAttribute('aria-label','Pause music')}).catch(()=>showToast('Tap the music button whenever you are ready'))}
function updateCakeTrackLabels(){cakeTrackLabels.forEach(label=>label.textContent=(cakeTrackIndex+1)+' / '+cakeTracks.length)}
function syncMusic(index){const wanted=musicForScene(index);if(currentAudio===wanted)return;const shouldResume=playing;currentAudio.pause();if(index===2){cakeTrackIndex=0;cakeAudio.src=cakeTracks[0];updateCakeTrackLabels()}currentAudio=wanted;currentAudio.volume=.42;if(shouldResume)currentAudio.play().catch(()=>{playing=false;musicToggle.classList.remove('is-playing');musicToggle.setAttribute('aria-label','Play music')})}
function toggleMusic(){if(playing){currentAudio.pause();playing=false;musicToggle.classList.remove('is-playing');musicToggle.setAttribute('aria-label','Play music')}else startMusic()}
scenes.forEach((scene,index)=>new MutationObserver(()=>{if(scene.classList.contains('is-active'))syncMusic(index)}).observe(scene,{attributes:true,attributeFilter:['class']}));
function changeCakeSong(fromButton=false){if(current!==2)return;cakeTrackIndex=(cakeTrackIndex+1)%cakeTracks.length;cakeAudio.src=cakeTracks[cakeTrackIndex];updateCakeTrackLabels();if(fromButton||playing){currentAudio=cakeAudio;cakeAudio.play().then(()=>{playing=true;musicToggle.classList.add('is-playing');musicToggle.setAttribute('aria-label','Pause music');if(fromButton)showToast('Birthday song '+(cakeTrackIndex+1)+' of '+cakeTracks.length+' ♫')}).catch(()=>{playing=false;musicToggle.classList.remove('is-playing')})}}
cakeAudio.addEventListener('ended',()=>changeCakeSong());
document.querySelectorAll('[data-cake-song]').forEach(button=>button.addEventListener('click',()=>changeCakeSong(true)));
function goTo(index){if(index<0||index>=scenes.length||index===current)return;prepareScene(index);const old=scenes[current],next=scenes[index];old.classList.add('is-leaving');setTimeout(()=>{old.hidden=true;old.classList.remove('is-active','is-leaving');next.hidden=false;requestAnimationFrame(()=>requestAnimationFrame(()=>next.classList.add('is-active')));current=index;backBtn.hidden=index===0;chapterCount.textContent=String(index+1).padStart(2,'0')+' / '+String(scenes.length).padStart(2,'0');progressFill.style.width=((index+1)/scenes.length*100)+'%';if(index===3)setTimeout(()=>document.querySelector('#bouquet').classList.add('is-bloomed'),500);if(index===6)burst(innerWidth/2,innerHeight*.55,150,true)},620)}
const beginBtn=document.querySelector('#beginBtn'),secretLock=document.querySelector('#secretLock'),secretCode=document.querySelector('#secretCode'),lockStatus=document.querySelector('#lockStatus');
document.addEventListener('pointerdown',()=>{if(current===0&&!playing)startMusic()},{once:true});
secretCode.addEventListener('input',()=>{secretCode.value=secretCode.value.replace(/\D/g,'').slice(0,4);secretLock.classList.remove('is-wrong')});
secretLock.addEventListener('submit',event=>{event.preventDefault();if(secretCode.value==='2307'){secretLock.classList.add('is-unlocked');lockStatus.textContent='Correct — welcome to Nandini’s little universe ♡';secretCode.disabled=true;secretLock.querySelector('button').disabled=true;burst(innerWidth*.24,innerHeight*.72,70,true);setTimeout(()=>{secretLock.hidden=true;beginBtn.hidden=false;beginBtn.focus()},700)}else{secretLock.classList.remove('is-wrong');secretLock.offsetHeight;secretLock.classList.add('is-wrong');lockStatus.textContent='Not quite… think of her special date ♡';secretCode.focus();secretCode.select()}});
beginBtn.addEventListener('click',()=>{startMusic();burst(innerWidth*.5,innerHeight*.55,100,true);setTimeout(()=>goTo(1),350)});
musicToggle.addEventListener('click',toggleMusic);
backBtn.addEventListener('click',()=>goTo(current-1));
document.querySelectorAll('[data-next]').forEach(btn=>btn.addEventListener('click',()=>goTo(current+1)));

let balloonIndex=0,balloonRevealTimer;const balloons=[...document.querySelectorAll('.balloon')],wordSlots=[...document.querySelectorAll('#wordReveal span')];
balloons.forEach((balloon,index)=>balloon.addEventListener('click',e=>{if(index!==balloonIndex){balloon.classList.add('is-wrong');showToast('This one is feeling shy… pop '+(balloonIndex+1)+' first 🎈');setTimeout(()=>balloon.classList.remove('is-wrong'),350);return}balloon.classList.add('is-popped');wordSlots[index].textContent=balloon.dataset.word;wordSlots[index].classList.add('is-visible');burst(e.clientX,e.clientY,42);balloonIndex++;if(balloonIndex===4){balloonRevealTimer=setTimeout(()=>{document.querySelector('.scene--balloons [data-next]').hidden=false;burst(innerWidth/2,innerHeight*.75,90,true)},500)}}));

function resetBalloons(){clearTimeout(balloonRevealTimer);balloonIndex=0;balloons.forEach(balloon=>balloon.classList.remove('is-popped','is-wrong'));wordSlots.forEach(slot=>{slot.textContent='';slot.classList.remove('is-visible')});document.querySelector('.scene--balloons [data-next]').hidden=true}

const wishStar=document.querySelector('#wishStar'),holdHint=document.querySelector('#holdHint'),blowBtn=document.querySelector('#blowBtn'),wishStatus=document.querySelector('#wishStatus'),candles=document.querySelector('#candles'),wishComplete=document.querySelector('#wishComplete'),cakeStage=document.querySelector('.cake-stage'),cakeLabel=document.querySelector('.cake-body small');let wishHoldTimer,wishRevealTimer,wishBlowTimer,wishActionTimer,wishSealed=false,cakeRound=1,awaitingSmile=false;
new MutationObserver(()=>document.querySelectorAll('[data-cake-song]').forEach(button=>button.hidden=!wishComplete.hidden)).observe(wishComplete,{attributes:true,attributeFilter:['hidden']});
function sealWish(){if(wishSealed)return;wishSealed=true;clearTimeout(wishHoldTimer);wishStar.classList.remove('is-holding');wishStar.classList.add('is-sealed');holdHint.textContent='wish sealed — the candles have it ♡';const from=wishStar.getBoundingClientRect(),to=document.querySelector('#candles').getBoundingClientRect(),comet=document.createElement('span');const dx=to.left+to.width/2-(from.left+from.width/2),dy=to.top+to.height/2-(from.top+from.height/2);comet.className='wish-comet';comet.textContent='✦';comet.style.setProperty('--from-x',(from.left+from.width/2)+'px');comet.style.setProperty('--from-y',(from.top+from.height/2)+'px');comet.style.setProperty('--dx',dx+'px');comet.style.setProperty('--dy',dy+'px');comet.style.setProperty('--mx',(dx*.55)+'px');comet.style.setProperty('--my',(dy*.25-70)+'px');document.body.appendChild(comet);burst(from.left+from.width/2,from.top+from.height/2,45,true);setTimeout(()=>comet.remove(),1400)}
function startWishHold(e){e.preventDefault();if(wishSealed)return;wishStar.classList.add('is-holding');holdHint.textContent='keep holding… breathe slowly and wish from your heart';wishStatus.textContent='The star is listening. Take all the time you need.';wishHoldTimer=setTimeout(()=>{sealWish();wishStatus.textContent='Beautiful. Your wish is sealed—blow only when you feel ready.'},3000)}
function cancelWishHold(){clearTimeout(wishHoldTimer);if(!wishSealed){wishStar.classList.remove('is-holding');holdHint.textContent='press & hold to seal your wish'}}
wishStar.addEventListener('pointerdown',startWishHold);['pointerup','pointerleave','pointercancel'].forEach(type=>wishStar.addEventListener(type,cancelWishHold));
function revealChocolateCake(){awaitingSmile=false;cakeRound=2;cakeStage.classList.add('is-changing');wishActionTimer=setTimeout(()=>{cakeStage.classList.add('is-chocolate');cakeStage.classList.remove('is-changing');cakeLabel.textContent='CHOCO • TRUFFLE';candles.classList.remove('is-out');document.querySelector('#candleGlow').style.opacity='';blowBtn.querySelector('span').textContent='Blow the chocolate-truffle candles';wishStatus.textContent='Meko tera fav cake flavour nhi pta.. toh dono options rkh diye.. 🍫🎂';burst(innerWidth*.72,innerHeight*.44,70,true)},500)}
function blowCurrentCake(){candles.classList.add('is-blowing');blowBtn.disabled=true;wishStatus.textContent=cakeRound===1?'Okay—first cake ki candles jaa rahi hain…':'Ab chocolate-truffle wali wish bhi universe ko bhejte hain…';wishBlowTimer=setTimeout(()=>{candles.classList.remove('is-blowing');candles.classList.add('is-out');document.querySelector('#candleGlow').style.opacity='0';burst(innerWidth*.73,innerHeight*.42,55,true)},700);if(cakeRound===1){wishRevealTimer=setTimeout(()=>{awaitingSmile=true;blowBtn.disabled=false;blowBtn.querySelector('span').textContent='Okay okay, smile kar diya 😌';wishStatus.textContent='Nandini..!! Smile toh krle acche se.. 😤📸'},1700)}else{wishRevealTimer=setTimeout(()=>{wishComplete.hidden=false;burst(innerWidth/2,innerHeight/2,150,true)},4700)}}
function beginCinematicBlow(){if(blowBtn.disabled)return;if(awaitingSmile){revealChocolateCake();return}if(candles.classList.contains('is-out'))return;if(!wishSealed)sealWish();blowBtn.disabled=true;blowBtn.querySelector('span').textContent='Take a deep breath… 3';wishStatus.textContent=cakeRound===1?'Your wish is sealed. Breathe in slowly…':'Chocolate-truffle wish ready. Breathe in slowly…';let count=3;wishActionTimer=setInterval(()=>{count--;if(count>0){blowBtn.querySelector('span').textContent=`Take a deep breath… ${count}`;wishStatus.textContent=count===2?'Hold that beautiful wish close…':'And now, gently blow ✨'}else{clearInterval(wishActionTimer);blowBtn.querySelector('span').textContent='Blowing the candles…';blowCurrentCake()}},900)}
blowBtn.addEventListener('click',beginCinematicBlow);

function resetWishScene(){clearTimeout(wishHoldTimer);clearTimeout(wishRevealTimer);clearTimeout(wishBlowTimer);clearInterval(wishActionTimer);wishSealed=false;cakeRound=1;awaitingSmile=false;wishStar.classList.remove('is-holding','is-sealed');holdHint.textContent='press & hold to seal your wish';candles.classList.remove('is-blowing','is-out');cakeStage.classList.remove('is-changing','is-chocolate');cakeLabel.textContent='23 • JULY';document.querySelector('#candleGlow').style.opacity='';wishComplete.hidden=true;blowBtn.disabled=false;blowBtn.querySelector('span').textContent='Take a breath & blow the candles';wishStatus.textContent='No rush. Make your wish properly—the candles will wait for you.';document.querySelectorAll('.wish-comet').forEach(comet=>comet.remove())}
function prepareScene(index){if(index===1)resetBalloons();if(index===2){resetWishScene();blowBtn.querySelector('span').textContent='Take a breath & blow the candles'}}

const quotes=[
'“Tumhari smile na, woh wali jagah hai jahaan mera har bura din aake theek ho jaata hai.”',
'“Tu sirf special nahi hai, tu woh rare si khushi hai jo sabki life mein nahi aati.”',
'“Tere saath normal se moments bhi favourite memories ban jaate hain—yeh talent sirf tumhare paas hai.”',
'“Bas aise hi rehna—thodi si pagal, bohot zyada pyaari, aur bilkul meri favourite.”'];
let quoteIndex=0;const quoteCard=document.querySelector('#quoteCard');document.querySelector('#nextQuote').addEventListener('click',()=>{quoteCard.classList.add('is-changing');setTimeout(()=>{quoteIndex=(quoteIndex+1)%quotes.length;quoteCard.querySelector('span').textContent=String(quoteIndex+1).padStart(2,'0')+' / 04';quoteCard.querySelector('blockquote').textContent=quotes[quoteIndex]},220);setTimeout(()=>quoteCard.classList.remove('is-changing'),470)});document.querySelector('#bouquet').addEventListener('click',e=>{e.currentTarget.classList.add('is-bloomed');burst(e.clientX,e.clientY,50,true)});

const strip=document.querySelector('#filmStrip');let dragging=false,startX,scrollStart;strip.addEventListener('pointerdown',e=>{dragging=true;startX=e.clientX;scrollStart=strip.scrollLeft;strip.setPointerCapture(e.pointerId)});strip.addEventListener('pointermove',e=>{if(dragging)strip.scrollLeft=scrollStart-(e.clientX-startX)*1.4});strip.addEventListener('pointerup',()=>dragging=false);strip.addEventListener('pointercancel',()=>dragging=false);

const memoryFigures=[...strip.querySelectorAll('figure')],photoModal=document.querySelector('#photoModal'),photoLarge=document.querySelector('#photoLarge'),photoCaption=document.querySelector('#photoCaption'),photoCount=document.querySelector('#photoCount');let photoIndex=0,dragDistance=0;
function renderLargePhoto(){const figure=memoryFigures[photoIndex],source=figure.querySelector('img');photoLarge.src=source.src;photoLarge.alt=source.alt;photoCaption.textContent=figure.querySelector('figcaption').textContent;photoCount.textContent=String(photoIndex+1).padStart(2,'0')+' / '+String(memoryFigures.length).padStart(2,'0');photoLarge.style.animation='none';photoLarge.offsetHeight;photoLarge.style.animation='photoReveal .45s cubic-bezier(.22,1,.36,1)'}
function openPhoto(index){photoIndex=index;renderLargePhoto();document.body.classList.add('photo-open');photoModal.hidden=false;photoModal.setAttribute('aria-hidden','false');document.querySelector('#photoBack').focus()}
function closePhoto(){photoModal.hidden=true;photoModal.setAttribute('aria-hidden','true');document.body.classList.remove('photo-open')}
function movePhoto(direction){photoIndex=(photoIndex+direction+memoryFigures.length)%memoryFigures.length;renderLargePhoto()}
memoryFigures.forEach((figure,index)=>{figure.addEventListener('pointerdown',()=>dragDistance=strip.scrollLeft);figure.addEventListener('click',()=>{if(Math.abs(strip.scrollLeft-dragDistance)<8)openPhoto(index)})});
document.querySelector('#photoClose').addEventListener('click',closePhoto);document.querySelector('#photoBack').addEventListener('click',closePhoto);document.querySelector('#photoPrev').addEventListener('click',()=>movePhoto(-1));document.querySelector('#photoNext').addEventListener('click',()=>movePhoto(1));photoModal.addEventListener('click',event=>{if(event.target===photoModal)closePhoto()});
document.addEventListener('keydown',e=>{if(photoModal.hidden)return;if(e.key==='Escape')closePhoto();if(e.key==='ArrowLeft')movePhoto(-1);if(e.key==='ArrowRight')movePhoto(1)});

const letterText=`Dear Nandini,\n\nHappy birthday to the person who has this beautiful habit of making ordinary days feel important just by being there.\n\nI hope you know how special you truly are—not only today, when everyone is reminding you, but on the quiet days too. You have a heart that makes people feel seen, a smile that can fix moods without even trying, and a presence that turns little moments into the memories we keep.\n\nThank you for being my safe place, my partner in nonsense, my unpaid therapist, and the best friend I could have asked life for. With you, laughter is louder, problems feel lighter, and even silence feels comfortable.\n\nOn your birthday, I wish I could hand you every bit of happiness you have unknowingly given the people around you. I hope this year is gentle with your heart, loud with your laughter, and full of the kind of magic you secretly wish for. May every dream you are scared to say out loud find its way to you.\n\nAnd whenever you doubt yourself, please remember: you are deeply loved, ridiculously precious, and completely irreplaceable. There is only one you—and I am so, so lucky that I get to call her my best friend.\n\nHappy Birthday, meri pyaari Nandini. Never shrink your sparkle. The world is much prettier with you in it. ♡`;
const envelope=document.querySelector('#envelope'),modal=document.querySelector('#letterModal'),typed=document.querySelector('#typedLetter');let typedOnce=false;
envelope.addEventListener('click',()=>{envelope.classList.add('is-open');setTimeout(()=>{modal.classList.add('is-visible');modal.setAttribute('aria-hidden','false');if(!typedOnce)typeLetter()},850)});
function typeLetter(){typedOnce=true;let i=0;const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;const step=()=>{typed.textContent=letterText.slice(0,i);i+=reduce?20:2;if(i<=letterText.length)setTimeout(step,reduce?1:16);else{typed.textContent=letterText;document.querySelector('#letterSign').hidden=false;document.querySelector('#letterNext').hidden=false;burst(innerWidth*.7,innerHeight*.8,55,true)}};step()}
document.querySelector('#closeLetter').addEventListener('click',()=>{modal.classList.remove('is-visible');modal.setAttribute('aria-hidden','true')});
const loveBtn=document.querySelector('#loveBtn'),loveMachine=document.querySelector('#loveMachine'),loveMeter=document.querySelector('#loveMeter'),loveLevel=document.querySelector('#loveLevel'),loveWish=document.querySelector('#loveWish');const birthdayWishes=['May your smile always come back twice as bright.','May every quiet dream in your heart find its way to you.','May this year bring soft days, loud laughter and safe love.','May you always see yourself through the eyes of people who adore you.','May 23 July keep returning with more magic than the year before.','May every ordinary day surprise you with one beautiful reason to smile.','May distance, time and busy days never change how deeply you are loved.','May the universe spoil you shamelessly—today and always.'];let loveClicks=0,infiniteLove=false,loveStormTimer;
function rainLove(count){for(let i=0;i<count;i++){const heart=document.createElement('span');heart.className='heart-flood';heart.textContent=['♡','♥','✦','Happy Birthday!'][i%4];heart.style.left=Math.random()*100+'vw';heart.style.bottom=(-20-Math.random()*170)+'px';heart.style.color=['#ffd3df','#f5b1c7','#f1c06c','#fff'][i%4];heart.style.fontSize=i%4===3?(10+Math.random()*7)+'px':'';heart.style.animationDelay=Math.random()*.7+'s';document.body.appendChild(heart);setTimeout(()=>heart.remove(),4400)}}
loveBtn.addEventListener('click',()=>{loveClicks++;const tier=Math.min(loveClicks,5),level=tier*20;loveMeter.style.width=level+'%';loveWish.textContent=birthdayWishes[(loveClicks-1)%birthdayWishes.length];loveLevel.textContent=tier<5?'Love level: '+level+'%':'Love level: ∞ INFINITE';loveBtn.querySelector('span').textContent=tier<5?'More love! Click again ('+tier+'/5)':'Send even more love';burst(innerWidth/2,innerHeight*.58,70+tier*25,true);rainLove(16+tier*7);if(tier===5&&!infiniteLove){infiniteLove=true;loveMachine.classList.add('is-infinite');document.querySelector('#finalNote').hidden=false;showToast('Infinite love mode unlocked for Nandini! ♡');loveStormTimer=setInterval(()=>rainLove(7),360);setTimeout(()=>clearInterval(loveStormTimer),7200)}});

const expectationBtn=document.querySelector('#expectationBtn'),expectationCard=document.querySelector('#expectationCard');
expectationBtn.addEventListener('click',()=>{expectationUnlocked=true;if(currentAudio!==expectationAudio){currentAudio.pause();currentAudio=expectationAudio}currentAudio.currentTime=0;currentAudio.volume=.46;currentAudio.play().then(()=>{playing=true;musicToggle.classList.add('is-playing');musicToggle.setAttribute('aria-label','Pause music')}).catch(()=>showToast('Tap the music button to play Tum Mile ♡'));expectationCard.hidden=false;requestAnimationFrame(()=>requestAnimationFrame(()=>expectationCard.classList.add('is-open')));expectationBtn.classList.add('is-open');expectationBtn.setAttribute('aria-expanded','true');expectationBtn.querySelector('strong').textContent='Tum Mile… play it once more';expectationBtn.querySelector('b').textContent='♡';burst(innerWidth/2,innerHeight*.72,110,true);rainLove(24);setTimeout(()=>expectationCard.scrollIntoView({behavior:'smooth',block:'center'}),450)});

const secretLines=['Nandini’s smile deserves its own national holiday.','Breaking news: birthday girl remains impossibly adorable.','Best-friend rating: 11/10, no notes.','She is sunshine with a little bit of pagalpan.','Plot twist: the prettiest part of this website is reading it right now.'];let secretIndex=0;
document.querySelector('#secretCompliment').addEventListener('click',event=>{showToast(secretLines[secretIndex%secretLines.length]);secretIndex++;burst(event.clientX||72,event.clientY||38,36,true)});
let lastCursorSpark=0;if(matchMedia('(pointer:fine)').matches){document.addEventListener('pointermove',event=>{const now=performance.now();if(now-lastCursorSpark<85)return;lastCursorSpark=now;const spark=document.createElement('span');spark.className='cursor-spark';spark.textContent=Math.random()>.5?'♡':'✦';spark.style.left=(event.clientX+7)+'px';spark.style.top=(event.clientY+5)+'px';spark.style.fontSize=(10+Math.random()*9)+'px';document.body.appendChild(spark);setTimeout(()=>spark.remove(),950)})}
window.addEventListener('resize',sizeCanvas);sizeCanvas();animate();

// Allows a specific chapter to be opened for visual QA: index.html?scene=4
const previewParams=new URLSearchParams(location.search),requestedScene=Number(previewParams.get('scene')),requestedPhoto=Number(previewParams.get('photo'));
if(Number.isInteger(requestedScene)&&requestedScene>0&&requestedScene<scenes.length){setTimeout(()=>goTo(requestedScene),80)}
if(Number.isInteger(requestedPhoto)&&requestedPhoto>0&&requestedPhoto<=memoryFigures.length){setTimeout(()=>openPhoto(requestedPhoto-1),1100)}
if(previewParams.get('love')==='test'){setTimeout(()=>loveBtn.click(),1200)}
